# Generated by Django 5.2.11 on 2026-02-12 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_remove_attendance_unique_attendance_per_day_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
    ]
